#!/usr/bin/env bun
import { $, ShellPromise } from 'bun';
import path from 'path';
import { z } from 'zod';

function runPlaybook(
  path: string,
  inventory: string[],
  vars: object,
): ShellPromise {
  return $`ANSIBLE_CONFIG=./ansible.cfg ansible-playbook ansible/${path} -i '${
    inventory.join(',') + ','
  }' --extra-vars '${JSON.stringify(vars)}'`;
}

const HostConfigSchema = z
  .object({
    type: z.string(),
    image: z.string(),
    location: z.string(),
    ssh_key_path: z.string(),
    ssh_pub_key_path: z.string(),
    stacks: z.array(z.string()), // TODO validate against real stacks
  })
  .strict();

async function deploy(hostname: string): Promise<void> {
  const hostConfigRaw = await Bun.file(`hosts/${hostname}/server.json`).json();
  const hostConfig = HostConfigSchema.parse(hostConfigRaw);

  await runPlaybook(
    'deploy/create-vps.yaml',
    ['localhost', hostname],
    {
      ...hostConfig,
      hostname: hostname,
      hosts_path: path.resolve('hosts/'),
      stacks_path: path.resolve('stacks/'),
      ssh_user: 'akmin',
      hcloud_token: Bun.env.HCLOUD_TOKEN,
      porkbun_api_key: Bun.env.PORKBUN_API_KEY,
      porkbun_secret_api_key: Bun.env.PORKBUN_SECRET_API_KEY,
    },
  );
}

async function main(): Promise<number> {
  const argv = process.argv.slice(2);
  if (argv.length < 1) {
    printHelp();
    return 1;
  }

  switch (argv[0]) {
    case 'deploy':
      if (argv.length < 2) {
        printHelp();
        return 1;
      }

      const missingVar = checkEnvVars();
      if (missingVar) {
        console.log(`${missingVar} must be set!`);
        return 1;
      }

      await deploy(argv[1]);
      break;
    default:
      printHelp();
      return 1;
  }

  return 0;
}

function printHelp(): void {
  console.log('usage: gravy deploy HOSTNAME');
}

function checkEnvVars(): string | undefined {
  const requiredEnvVarNames = [
    'HCLOUD_TOKEN',
    'PORKBUN_API_KEY',
    'PORKBUN_SECRET_API_KEY',
  ];

  for (const varName of requiredEnvVarNames) {
    if (!Bun.env[varName]) {
      return varName;
    }
  }
}

main()
  .then(process.exit)
  .catch((err) => {
    console.error('Error:', err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
